parser: babel-eslint
extends:
  - airbnb
  - prettier
plugins:
  - flowtype
env:
  browser: true
rules:
  eqeqeq: ['error', 'allow-null']
  no-unused-expressions:
    - error
    - allowShortCircuit: true
  no-use-before-define: off
  no-multi-spaces: off
  no-nested-ternary: off
  no-cond-assign: ['error', 'except-parens']
  no-underscore-dangle: off
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: ignore
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-continue: off
  no-await-in-loop: off
  no-mixed-operators: off
  no-duplicate-imports: off
  no-confusing-arrow: off
  key-spacing:
    - warn
    - beforeColon: false
      afterColon: true
      mode: 'minimum'
  object-property-newline: off
  class-methods-use-this: off
  arrow-parens: off
  prefer-destructuring: off
  react/sort-comp: off
  react/jsx-first-prop-new-line: off
  react/jsx-indent: off
  react/jsx-indent-props: off
  react/jsx-closing-bracket-location: off
  react/jsx-filename-extension: off
  react/jsx-boolean-value: off
  react/forbid-prop-types: off
  react/prop-types: off
  react/no-unused-prop-types: off
  react/require-extension: off
  react/require-default-props: off
  react/prefer-stateless-function: off
  react/jsx-max-props-per-line: off
  react/jsx-wrap-multilines: off
  react/jsx-closing-tag-location: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
      peerDependencies: true
      optionalDependencies: false
  import/prefer-default-export: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/href-no-hash: off
  jsx-a11y/label-has-for: off
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/click-events-have-key-events: off
globals:
  # Legacy
  React$Component: false # remove when input HOC is upgrade to Flow 66
  # Flow
  Class: false
  $Exact: false
  SyntheticEvent: false
  SyntheticWheelEvent: false
  SyntheticKeyboardEvent: false
  SyntheticMouseEvent: false
  SyntheticClipboardEvent: false
  WheelEvent: false
  Event: false
  KeyboardEvent: false
  HTMLElement: false
  HTMLInputElement: false
  IntervalID: false
  TimeoutID: false
  # Jest
  $: false
  mockComponent: false
